config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :spells
  # get 'spells/search', to: 'spells#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pathfinder_class.rb
class PathfinderClass < ApplicationRecord
  has_many :spell_levels
  has_many :spells, through: :spell_levels

  CLASSES = %w(
    alchemist
    antipaladin
    bard
    bloodrager
    cleric
    druid
    hunter
    inquisitor
    investigator
    magus
    medium
    mesmerist
    occultist
    oracle
    paladin
    psychic
    ranger
    shaman
    skald
    sorcerer
    spiritualist
    summoner
    witch
    wizard
  ).freeze

  validates :name, inclusion: { in: CLASSES }
  validates :name, uniqueness: true
end

app/models/spell.rb
class Spell < ApplicationRecord
  has_many :spell_levels
  has_many :pathfinder_classes, through: :spell_levels

  SCHOOLS = %w(
    abjuration
    conjuration
    divination
    enchantment
    evocation
    illusion
    necromancy
    transmutation
    universal
  ).freeze

  validates :name, presence: true
  validates :school, inclusion: { in: SCHOOLS }
  validates :casting_time, presence: true
  validates :source, presence: true
  validates :dismissible, inclusion: { in: [true, false] }
  validates :description, presence: true
  validates :spell_requirements, length: { is: 4 }

  validate :validate_spell_requirements

  default_scope { order(:name) }
  paginates_per(50)

  def validate_spell_requirements
    self.spell_requirements.values.each do |req_value|
      if ![true, false].include?(req_value)
        errors.add("Spell requirements", "All values for the spell requirements must be true or false.")
      end
    end
  end

  def validate_class_requirements
    self.class_requirements.values.each do |req_value|
      if req_value.class != Integer && req_value != nil
        errors.add(
          'requirements',
          'All values for the class requirements must be an integer or nil.',
        )
      end
    end
  end

  def list_spell_requirements
    display = ""
    spell_requirements.each do |requirement, value|
      if value
        display << requirement[0]
      end
    end

    display = if display.include?("f")
                display.split("").sort.reverse!
              else
                display.split("")
              end

    display.join(", ")
  end
end

app/models/spell_level.rb
class SpellLevel < ApplicationRecord
  belongs_to :pathfinder_class
  belongs_to :spell
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    return self.role == "admin"
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hello_world_controller.rb
# frozen_string_literal: true

class HelloWorldController < ApplicationController
  layout 'hello_world'

  def index
    @hello_world_props = { name: 'Bad Boy Mcgee' }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # Just render the show page as the home page for the site
  def show; end
end

app/controllers/spells_controller.rb
class SpellsController < ApplicationController
  def index
    @spells = SpellFinder.perform(spells_params)
    @class_list = PathfinderClass::CLASSES
  end

  def show
    @spell = Spell.find(params[:id])
  end

  private

  def spells_params
    params.permit(:class_name, :level, :page)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(:id)
  end

  def show
    @user = User.find(params[:id])
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spells_helper.rb
module SpellsHelper
end

app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component("HelloWorld", props: @hello_world_props, prerender: false) %>

app/views/home/about.html.erb
<br>About page

app/views/home/show.html.erb
<h1> Pathfinder Companion Home Page </h1>

<%= react_component('Main') %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PfCompanion</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/spells/_search_and_filter.html.erb
 <%#this will have the search bar and filter check boxes %>

<p>Search and filter area</p>

<%= form_tag spells_path, method: 'get' do %>
  <%= label_tag :q, 'Class:' %>
  <%= select_tag 'class_name', options_for_select(@class_list) %>
  <%= submit_tag("Submit") %>
<% end %>

app/views/spells/index.html.erb
<h1>These are all the spells!</h1>

<%= render "search_and_filter" %>

<table id="spellsTable" class="tablesorter">
  <thead>
    <tr>
      <th width="250">Spell Name</th>
      <th width="150">School</th>
      <th width="50">Components</th>
      <th width="150">Source</th>
    </tr>
  </thead>
  <tbody>
    <% @spells.each do |spell| %>
    <tr>
      <td><%= link_to "#{spell.name.titleize}", spell_path(spell) %></td>
      <td><%= spell.school.titleize %></td>
      <td><%= spell.list_spell_requirements.upcase %>
      <td><%= spell.source %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/spells/show.html.erb
<%= link_to "Back to Spells", spells_path %>

<h1><%= @spell.name.titleize %></h1>
<ul>
  <li>School: <%= @spell.school %></li>
  <li>Source: <%= @spell.source %></li>

  <li>Range: <%= @spell.range %></li>
  <li>Targets: <%= @spell.targets %></li>
  <li>Casting Time: <%= @spell.casting_time %></li>
  <li>Duration: <%= @spell.duration %></li>
  <li>Dismissible: <%= @spell.dismissible %></li>

  <li>Spell Resistance: <%= @spell.spell_resistance %></li>
  <li>Saving Throw: <%= @spell.saving_throw %></li>
  <li>Requirements: <%= @spell.list_spell_requirements.upcase %></li>

  <br>

  <li><%= @spell.description %></li>
</ul>

app/views/users/index.html.erb
<h1>users index!</h1>

<% @users.each_with_index do |user, index| %>
  <%= index + 1 %>
  <%= link_to "#{user.email}", user_path(user) %>
  <br>
<% end %>

app/views/users/show.html.erb
<h1>This is the user show page for <%= @user.email %> </h1>